### ISSUE TITLE
Fix bundling for mac causing a white screen

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#53] opened 2022-09-30 16:47 UTC
Right now if we bundle for mac, it "works" but creates a white screen. We should find out why and fix it (obviously)

**Comment by calogero93** [comment] 2022-10-05 14:26
Finally I found the problem with white screen and open-close app issue,

When we deal with creation of a file/directory here:
`std::fs::create_dir_all(DEFAULT_PATH.read().clone()).is_err().expect("Error creating directory");`

and here:
`let file_appender =
        tracing_appender::rolling::hourly(DEFAULT_PATH.read().join("logs"), "warp-gui.log");`

we get this error `Read-only file system (os error 30)`
This is because the application tried to create file/directory in the same environment of running app that is read-only for security purpose.


The solution is to change path in DEFAULT_PATH pointing to main environment like home directory, document directory or whatever, using `dirs` crate and create the folder .warp there for example.

Now it's working on my side

**Comment by tooshel** [comment] 2022-10-06 14:31
I ran "make install" and the dmg opened up and I was able to run it right there and also if I copied it to my "applications" folder. We good to close this out or are we waiting for Phill to test it?

**Comment by tooshel** [comment] 2022-10-06 16:36
In standup it came up that the issue is that saving isn't working .. . . i.e. the app opens but when you go back you have to create another account.

**Comment by dariusc93** [comment] 2022-10-06 18:15
> In standup it came up that the issue is that saving isn't working .. . . i.e. the app opens but when you go back you have to create another account.

Might be related to #100 ?

**Comment by calogero93** [comment] 2022-10-07 11:32
> In standup it came up that the issue is that saving isn't working .. . . i.e. the app opens but when you go back you have to create another account.

I tried more than once but I have no problem, I deleted the .warp directory and try to create another account, close the bundled app and open it again and I had no problem, my account is there.
Can you help me to reproduce this issue?

**Comment by InfamousVague** [comment] 2022-10-07 16:34
https://github.com/Satellite-im/Uplink-Desktop/pull/105

**Comment by dariusc93** [comment] 2022-10-11 15:39
Is this resolved? @tooshel

**Closed as completed** 2022-10-25 04:41 UTC
