### ISSUE TITLE
CircleCI does not build ubuntu correctly.

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#94] opened 2022-10-03 21:58 UTC

**Comment by dariusc93** [comment] 2022-10-06 06:20
Is this still an issue?

**Comment by dariusc93** [comment] 2022-10-12 02:12
pinging @InfamousVague

**Comment by dariusc93** [comment] 2022-10-12 22:52
Closing as this should be resolved. Can reopen if the issue isnt

**Closed as completed** 2022-10-12 22:52 UTC
Labels: question
