### ISSUE TITLE
Compose pushes new messages into jumbled mess.

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#21] opened 2022-09-16 16:45 UTC
See screenshot, needs investigation I assume it's a simple HTML / CSS issue but all of the chats are crammed together when pushing new messages to the conversation, see screenshot.

![image](https://user-images.githubusercontent.com/1770198/190688846-e710ea50-12d7-4e0d-a880-460e4bd2ecf9.png)

**Comment by tooshel** [comment] 2022-09-22 17:12
Note that this started to happen when we switched to using the github version of [dioxus](https://github.com/DioxusLabs/dioxus) as opposed to the crate. 

I also noticed that for whatever reason we didn't switch to the github version of dioxus-html so we might want to try that and see what happens.
![image](https://user-images.githubusercontent.com/223338/191809919-77f3a477-c8b9-4d4f-991d-50336f3700fb.png)

**Comment by dariusc93** [comment] 2022-09-23 07:10
Was fixed in #22

**Comment by dariusc93** [comment] 2022-09-23 07:41
Looks like it partially fixed the issue while doing additional testing but the issue is still on-going it seems

EDIT: 
![image](https://user-images.githubusercontent.com/3918024/191913660-fd6ceeb8-7b99-4960-b94c-6f8564f546a5.png)

**Comment by dariusc93** [comment] 2022-09-24 02:55
This was resolved by reverting changes in dev

**Closed as completed by dariusc93** 2022-09-24 02:55 UTC
Labels: bug

**Comment by InfamousVague** [comment] 2022-09-26 19:06
Might come back when we go to update again, closing for now.
